### ISSUE TITLE
Cache Elm Dependencies to Speed-up Build on Circle-CI

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#116]
At present one of our projects takes **8 _minutes_** to download and compile the Elm App:
![image](https://user-images.githubusercontent.com/194400/42029867-d5807dae-7ac8-11e8-86fb-b9a90f0a1112.png)

## Todo

+ [ ] Figure out how to cache elm dependencies on CircleCI (_we will do Travis-CI second_)
+ [ ] Apply to CI Client Project.
+ [ ] Write-up steps with sample code in `learn-elm` and link to from `learn-circleci` 

`Priority-1` because this wastes time _every_ CI build which slows down our dev workflow... ⏳ 💸 🔥 
@SimonLab if you have time to help investigate this please go for it! (_otherwise I will look at it soon..._)

**Comment by nelsonic** [comment]
One of our projects just took ***44 minutes*** to run `elm compile` ... 😮 ⏳ 
![image](https://user-images.githubusercontent.com/194400/46549113-e4a78b80-c8c8-11e8-8a4a-63ba66984fe5.png)
