### ISSUE TITLE
Why We Still Choose (and Recommend) Elm in 2019?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#129]
# Why?

In 2016 when we were considering our options for how to build an upcoming web app/project,
we opened the "***Why***?" issue #1 to capture our initial reasoning for shortlisting Elm. 
In the interest of _balance_ we _also_ opened a "**Why _NOT_**?" #2 to concisely capture the _counter-points_.
_Sadly_, `some` people have _chosen_ to focus on the "Why NOT?" from ***2016*** and _ignore_ the fact that _everything_ in Elm-lang and it's _wonderful_ community has gotten _much_ better in the last **27 Months**!

# _Who_ is this for?

If you have _already_ made up your mind on your technology choices for whatever reason and are a die-hard fan of a particular language, framework or paradigm, this is _not_ for you. 
_Thank you_ for reading this far and _have a **great day**_! 

This post is for anyone who is either _considering_ what programming language / architecture to use for their web application or is joining a team that _already_ has an Elm App and wants to _understand_ the reasoning behind why the Elm language and architecture is the _appropriate_ choice for the project.

Our goal is to help Lead developers or CTOs have a _reference_ they can share with their team which _comprehensively_ illustrates the **_business_ case** for _why_ choosing Elm will _directly/objectively_ result in a better _user experience_ (_faster page load time, no errors and more responsive UI!_), better developer experience (_friendly compiler warnings, faster compilation and clear upgrade instructions!_) and thus lead to a better ***bottom line*** for the company using Elm!

# What?

A _lot_ has changed in the last couple of years and we feel it's worth updating and sharing our thoughts,
in case someone out there is in the same position as we were (_trying to decide if they should use Elm_) and can use some _perspective_ in their decisions making. 

Elm's creator Evan Czaplicki @evancz is an _incredibly_ talented and visionary coder but he is _not_ a "salesman" and is not _actively trying_ to do any "marketing" for Elm. Instead he is _focussed_ on making Elm the most _reliable_ programming language for building User Interfaces (UI). Elm does not have a _megaphone_ or army of "pushers" who's _one job_ it is to get devs to use it.

Frameworks like React.js have an _mountain_ of cash from [Facebook](https://github.com/dwyl/learn-react/issues/23) for marketing to get developers to use it. It makes sense for Fb to pay "developer advocates" and meetup organisers to promote React because then they have a built-in "talent pool" they can recruit from. React.js is _technically_ "_worse_" than Elm in almost _every_ respect but people in the Elm community are too "nice" or "polite" to say it because nobody wants to be "negative" about the _other_ frameworks. This is _admirable_ and we should _all_ strive to "speak no evil", but it means that nobody is making the _case_ for Elm and so other frameworks are "winning" in _popularity_. 

As we know from Coca Cola's example, aggressive **marketing buys mindshare** and drives ["adoption"](https://money.cnn.com/2018/02/20/news/companies/cola-wars-coke-pepsi/index.html), but it does nothing to make the _product_ any better. Sure, Coca Cola is the "_most popular_" soft drink on the planet, but **plain tap _water_** is **_miles_ better** for your _health_ and won't [rot your teeth](https://healthyeating.sfgate.com/reasons-soda-rots-teeth-2949.html) or cause [obesity](https://www.nytimes.com/2009/09/01/nyregion/01fat.html)!

![image](https://user-images.githubusercontent.com/194400/53196157-39953580-360f-11e9-9881-f7790cbd878b.png)

Would you give Coca Cola to someone you _care_ about? Or would you pour them a glass of *Water*? 🚰 

> Note: my intention is ***not*** to write a "**Elm `vs.` React**" post which will _sound_ like I'm "_bashing_" React. All I want to do is lay out the _facts_ that Elm is a _perfectly_ good choice for building a "Modern" Web Application that is _reliable_ and performant. If people _chose_ to use React and do so based on more than a "popularity contest" (_i.e. "everyone's doing it_") that's _fine_. But _someone_ needs to make a _comprehensive_ "case" for Elm that _informed_ people can read and  _decide_. 

# Outline

Areas I intend to cover in the post include:
+ [ ] Briefly highlight _our_ experience using Elm in production for Fortune 500 Companies, Startups, etc.
  > **Note**: this is NOT a "pitch" for @dwyl to build anyone's app, we have more than enough clients/work and we aren't considering any more projects!
+ [ ] **Learning Curve** is _much_ flatter because _many_ learning resources are available!
  + [ ] The "official" book: [https://gitbook.com/book/evancz/an-introduction-to-elm](https://legacy.gitbook.com/book/evancz/an-introduction-to-elm/details) is ***Free*** and updated by both the language creator/maintainer and the _community_. _Anyone_ can download the PDF/eBook and learn the language (_by following examples_) in a day or two. 
  + [ ] Published Book: https://www.amazon.com/Web-Applications-Elm/dp/1484226097
    This book was **_published_ August 22, 2018**.
     + [ ] _Many_ more excellent eBooks available e.g:
       + [ ] https://elmprogramming.com by Pawan Poudel @pawanpoudel
       + [ ] https://www.manning.com/books/elm-in-action by Richard Feldman @rtfeldman
       + [ ] https://pragprog.com/book/jfelm/programming-elm by Jeremy Fairbank @jfairbank
  + [ ] Podcast: [elmtown.simplecast.fm](https://elmtown.simplecast.fm) hosted by programming _legend_ Kevin Yank. @sentience
  + [ ] Hundreds of Tutorials and Blog Posts: https://github.com/isRuslan/awesome-elm
    + Gentle Intro to Elm Architecture: [github.com/dwyl/learn-elm-architecture-in-javascript](https://github.com/dwyl/learn-elm-architecture-in-javascript)
    + Elm Architecture (in JS) TDD Todolist Tutorial: https://github.com/dwyl/todo-list-javascript-tutorial 
+ [ ] Hiring or _Training_ People to use Elm is _much_ easier in 2019
  + [ ] Community: https://elm-lang.org/community > Slack!
  + [ ] Forums: https://discourse.elm-lang.org
  + [ ] Meetups: [meetup.com/topics/elm-programming](https://www.meetup.com/topics/elm-programming) (25,172 members! 88 groups. 28 countries)
    + [ ] London: https://www.meetup.com/Elm-London-Meetup 934 members
    + [ ] New York: https://www.meetup.com/Elm-NYC (662 members)
    + [ ] Cambridge: https://www.meetup.com/elm-cambridge (135 members)
    + [ ] Berlin: https://www.meetup.com/Elm-Berlin (337 members)
    + [ ] Chicago: https://www.meetup.com/chicago-elm (558 members)
    + [ ] Copenhagen: https://www.meetup.com/Elm-Copenhagen (372 members)
    + [ ] Paris: https://www.meetup.com/Meetup-Elm-Paris (432 members)
    + [ ] Oslo: https://www.meetup.com/oslo-elm-meetup (472 members)
    + [ ] Prague: https://www.meetup.com/ElmPrague (274 members)
    + [ ] Amsterdam: https://www.meetup.com/Elm-Amsterdam (226 members)
    + [ ] Fortaleza (Brazil): https://www.meetup.com/FOR-Fun (395 members)
    + [ ] Tampa (Florida, USA): https://www.meetup.com/Ybor-Tech (739 members)
  + [ ] _Hundreds_ of **Freelancers** on UpWork: https://www.upwork.com/hire/elm-freelancers 
![elm-freelancers-upwork](https://user-images.githubusercontent.com/194400/53192643-e4552600-3606-11e9-8d5e-855aee5e5538.png)
  + [ ] Over a Thousand Questions/Answers on: [stackoverflow.com/questions/tagged/elm](https://stackoverflow.com/questions/tagged/elm)
+ [ ] **_Total_ Cost of Ownership** for the _lifetime_ of the project is _considerably_ lower than other frameworks because maintenance (_the majority of the life of an application_) is _much_ easier due to compiler warnings which _prevent_ changes to your app that don't compile. 
+ [ ] **No Run-time Errors** - zero chance of an Elm program throwing an error which "breaks" the UI!
+ [ ] ***Maintainability*** - if it doesn't compile it won't run! Safety guarantee is built-in. 
  + [ ] **_Enforced_ Semantic Versioning**! Means that if something changes in a package that you _depend_ on (_a "dependency"_) the author of that dependency is _forced_ to update the version number which means _you_ will receive a warning that it is no longer compatible with your App, i.e. _impossible_ to "break" _production_!!
+ [ ] **Who** is _Using_ Elm?
  + [ ] **IBM!** https://discourse.elm-lang.org/t/ibm-releases-elm-powered-app/2364
  _Direct_ quote: "_**`Elm`** is **really bullet proof**, it’s **not fake advertisement.**_"
  The release notes from IBM devs are not "all roses" but rather they are _balanced_ and have _constructive_ feedback, but their conclusion was: "_it’s really **amazing**._"
  + [ ] _Many_ more companies: https://github.com/jah2488/elm-companies
  + [ ] If you know of companies using elm that _aren't_ on the ["elm-companies"](https://github.com/jah2488/elm-companies) list, **please _share_**!!
+ [ ] Performance: The Elm Virtual Dom is _demonstrably_ faster than React.js (_etc!_) the _bundle_ size is _always_ smaller which means rendering the "first paint" is _always_ faster on _all_ browsers/devices. see: https://elm-lang.org/blog/small-assets-without-the-headache
+ [ ] **Open Source** Package Ecosystem: https://package.elm-lang.org _millions_ of hours worth of "***Free***" code you can use in your project which are _guaranteed_ to not "break" because of semantic versioning! 
+ [ ] Elm-UI https://github.com/mdgriffith/elm-ui makes pixel-perfect responsive layout _easy_!
+ [ ] Progressive Web Apps: 
  + @ceddlyburge wrote a _great_ post detailing how to build an PWA in Elm: 
  https://codeburst.io/how-to-make-an-elm-app-progressive-d2e17d2f6fea
  + @Birowsky wrote about the "tears of joy" building a PWA in Elm: 
  https://medium.freecodecamp.org/web-is-ready-for-you-on-line-elm-d3aa14dbf95
  + Open Source Example PWA in Elm: https://github.com/fpapado/ephemeral
+ [ ] Server Side Rendering. While Elm is not "_officially_" for SSR, _plenty_ of people are doing it!
  + [ ] https://github.com/rogeriochaves/spades (_@rogeriochaves is very helpful online!_)
  + [ ] http://pietrograndi.com/server-side-rendering-with-elm/
  + [ ] https://medium.com/@l.mugnaini/server-side-rendering-with-elm-9064170eb3cf
+ [ ] SEO: Google Bot ***executes*** your Elm App the _same_ way it would a JavaScript (React/Angular/etc.) app so there is no SEO "penalty" for building your SPA using Elm!
see: https://medium.com/@l.mugnaini/spa-and-seo-is-googlebot-able-to-render-a-single-page-application-1f74e706ab11
+ [ ] Apps built with Elm are _much_ more _lightweight_ than other front-end frameworks and _most_ cases will load in under a second on a mobile connection. We _often_ see cases of Mobile Web Apps built with other web frameworks that have a 1mb+ "bundle" which takes **10 seconds** to load on 3G!!

We recently wrote about "_**Why** I/We Would Still Pick **`Elixir`** in **2019**_" https://github.com/dwyl/learn-elixir/issues/102
and the response was overwhelmingly positive in the wider developer community (Hacker News)
see: https://news.ycombinator.com/item?id=18838115
My intention is do something _similar_ for Elm in 2019 but in _even_ more detail & examples 
with a view to helping others who are _considering_ Elm make their decision with _evidence_. 

I expect that this post is going to take me a couple of days to write (_with extensive links and images_) 
and I will seek feedback from the community to ensure that it is _concise_ and _fact-checked_. 
It will be a "20 minute read", but by the end of that, the person will _know_ that Elm a _solid_ choice!
I intend to _publish_ the writing as a post on **HackerNoon**: 
https://hackernoon.com/how-to-contribute-a-story-to-hacker-noon-1536c2587063
but if for any reason it does not meet the requirements for their content I will publish it directly on Medium for maximum exposure and built-in feedback. 

# What _`else`_ should be covered? (Help Wanted!)

+ Have _you_ faced any obstacles getting people at your company to adopt Elm?
+ What were the common "_objections_" (_besides "React has more packages..."_).
+ What did it take to _convince_ your "boss" to use Elm?
+ Can you _share_ links to "success stories" that we can include?

**Comment by nelsonic** [comment]
Requested _Help_ from the Elm Community: https://discourse.elm-lang.org/t/elm-needs-your-help/3193

**Comment by ronanyeah** [comment]
From 2017: https://www.pivotaltracker.com/blog/Elm-pivotal-tracker

> To sum it up, our manager has mandated that all new code be written in Elm.

**Comment by popara** [comment]
* What did it take to _convince_ your "boss" to use Elm?

I am working on a finance app with a friend that is domain expert and financier of the project. We had somewhat complex application developed in Angular1. In 2016 I introduced one Elm module that calculated some data. Slowly but surely (less than two weeks) I had rewritten whole update logic in Elm, and  let Angular still to do the rendering, because we had Highcharts.js on our pages. 

After a month of that weird setup I have rolled my sleeves and moved all `view`  rendering to Elm - with the exemption of those Highcharts, that I handled trough ports and previously mentioned. 

By that time I already had some complex business logic fixed, and refactored inside the Elm - and the benefits were obvious. I had 0 code crashes, I could refactor and play around and be sure that It won't break. Even though I didn't know for sure what I was doing, (eg. it was my only Elm project) we were more productive with only issues being that we sometimes couldn't figure out what to do, but Elm worked with us and helped me model the Domain which let to much faster iterations on ideas. 

But real benefit was when I removed Highcharts and made charts in Elm. Startup time was so much faster, the thing was smooth, no big hickups when we need to initialize Highcharts, it was smooth and fast, fast fast! Since then, and that was mid 2017. my partner on the project started to love it, and feel real benefits. 

I am only developer on the project, and I manage 45k lines of elm, alone, without fear of going crazy. 

You can check it out on chartbehavior.com --- we are preparing to release redesigned version with 0.19 in couple of days. 

To get a glimpse of performance and feeling, visit this link (comparing Facebook, Twitter and IBM stocks) 
https://chartbehavior.com/app#viz/FB%20TWTR%20IBM/2015/2019/cy/4

**Comment by nelsonic** [comment]
@ronanyeah thanks for sharing the link to @jschomay's great post on Pivotal Tracker blog! 👍 
@popara your work on https://chartbehavior.com is _impressive_! The interactive charts are _slick_!

**Comment by nelsonic** [comment]
Security in the Elm Ecosystem: https://discourse.elm-lang.org/t/security-in-the-elm-eco-system/2512
shared by Kasper in https://discourse.elm-lang.org/t/making-the-case-for-elm-at-my-company-looking-for-help/3193/18

**Comment by Maxim-Filimonov** [comment]
I’m facing this obstacle exactly and majority of my team is keen to use Elm. However, CTO’s is concerned that it’s going to be hard to hire people with Elm knowledge and that no one will be able to maintain this unknown language. 
I think sharing success stories of handing over large elm codebases to new developers and effects on hiring would be help greatest in discussion pro elm

**Comment by popara** [comment]
@Maxim-Filimonov Best way to disway that myth is to bring CTO to watch you training new team member how to work on Elm code, how fast they will pick it up, and become reliant contributor to the project.

**Comment by nelsonic** [comment]
While not _immediately_ obvious to most recruiters/HR, there is a _steady_ stream of qualified candidates for working in **`Elm`** coming out of _many_ of the World's Top universities & colleges. 
An _often_ overlooked fact that **`Elm`** is a _simplified subset_ (_only the essential parts_) of **`Haskell`** for the _front-end_. In other words, people who learn Haskell can adopt Elm in an _afternoon_. 

_Historically_, schools and universities have taught students procedural or object oriented languages.
I know this from experience of having been to computer science lectures at Edinburgh University where C++ and Java were the de facto languages at the time and everything else was ignored. 
(_thankfully, Edinburgh has seen the "light" and now teaches FP, see below, but wasn't always that way!_)
_Most_ universities now cover Functional Programming and _many_ teach FP a the _first_ programming paradigm because it's easier to _reason_ about certain algorithms from an FP perspective. 


# Universities Teaching Haskell λ

This list is a good starting point: https://wiki.haskell.org/Haskell_in_education but it's not exhaustive or up-to-date. Here is a _brief_ list of the world's _top_ universities teaching Haskell to both undergraduates and grads:

+ Harvard: https://www.seas.harvard.edu/courses/cs152/2016sp
+ MIT: https://innovation.mit.edu/event/haskell/
+ Stanford: http://cs242.stanford.edu/f18
+ Yale: https://cpsc.yale.edu/research/research-areas/programming-languages
+ Princeton: http://www.cs.princeton.edu/~dpw/cos441-11/
+ Oxford: https://www.cs.ox.ac.uk/teaching/courses/fp
+ Cambridge: https://www.cl.cam.ac.uk/teaching/1415/L28/
+ Imperial College, London: http://wp.doc.ic.ac.uk/ajf/the-haskell-programming-course
+ St. Andrews: https://www-fp.cs.st-andrews.ac.uk
+ Edinburgh University: http://www.inf.ed.ac.uk/teaching/courses/inf1/fp
+ Glasgow Univeristy: https://www.gla.ac.uk/coursecatalogue/course/?code=COMPSCI4021
  Also: https://www.futurelearn.com/courses/functional-programming-haskell/4 (_Free Online Course_)
+ Bristol: [http://www.bris.ac.uk/engineering/departments/computerscience](http://www.bris.ac.uk/engineering/departments/computerscience/courses/undergraduate/compscience.html)

This is a _short_ list that barely scratches the surface. 
Virtually _every_ _top tier_ university in every country is teaching Haskell.

Chris Smith has been teaching Haskell to children for several years
[![image](https://user-images.githubusercontent.com/194400/53621690-3988cd00-3bef-11e9-8dda-816a2d1a3f4d.png)](https://youtu.be/7CGuI9HcfqQ)
https://youtu.be/7CGuI9HcfqQ

_Anyone_ can learn online for free:  https://code.world
![code.world-haskell](https://user-images.githubusercontent.com/194400/53621749-76ed5a80-3bef-11e9-97bd-74d6520fb799.png)

[![image](https://user-images.githubusercontent.com/194400/53626591-07329c00-3bfe-11e9-8ef2-284d02bf6f9d.png)](https://youtu.be/02_H3LjqMr8)
https://youtu.be/02_H3LjqMr8



# The _Next_ Generation of `Elm` Programmers

[![image](https://user-images.githubusercontent.com/194400/53622799-f3ce0380-3bf2-11e9-8359-79c1556217d6.png)](https://youtu.be/G-GhUxeYc1U)
https://youtu.be/G-GhUxeYc1U


Teodor Lunaas Heggelund @teodorlu is teaching Elm to Kids via Code Club

[![image](https://user-images.githubusercontent.com/194400/53621864-e82d0d80-3bef-11e9-801e-6cc2578eebae.png)](https://youtu.be/FSec8QmgEWo)
https://youtu.be/FSec8QmgEWo
Slides: http://www.teodorheggelund.com/static/teaching-kids-elm.pdf
Topic: https://discourse.elm-lang.org/t/video-teaching-kids-to-code-with-elm-at-oslo-code-club-oslo-elm-day-2019/3200

## _Enjoying_ Coding

Most managers who _don't_ write code don't _want_ to think about the _possibility_ that people might _enjoy_ doing their work. Enjoying work is an _alien_ concept to _many_ people who treat their job as a means to an end; a paycheque. 

Make Web Apps Fun to Build and Easy to Refactor with Elm ~ Daniel Bachler @danyx23
[![image](https://user-images.githubusercontent.com/194400/53623125-1280ca00-3bf4-11e9-9e56-ece4ba7cb620.png)](https://youtu.be/ehtn81p06Ow)
https://youtu.be/ehtn81p06Ow
https://elmbridge.github.io/curriculum

Developer Happiness on the Front End with Elm ~ Kevin Yank @sentience
[![image](https://user-images.githubusercontent.com/194400/53624266-94bebd80-3bf7-11e9-8c7b-e3eb156fcc40.png)](https://youtu.be/kuOCx0QeQ5c)
https://youtu.be/kuOCx0QeQ5c

I'm _incredibly_ optimistic that the people who **_proactively_ learn** something intellectually interesting are gravitating to FP in general and Elm _specifically_. 

We _all_ know that OO is not "going away" ... in the same way that [religious dogmatism](https://github.com/nelsonic/nelsonic.github.io/issues/685) is here to stay.
But one thing _acutely_ aware of is that Machine Learning will be doing the jobs of most programmers in the next 20 years ... https://github.com/nelsonic/nelsonic.github.io/issues/318 so the FP vs. OO debate will be **moot**! 😮 
Until then I'm going to _enjoy_ reading, writing & maintaining FP programs (Elm/Elixir/Haskell).

**Comment by ceddlyburge** [comment]
I have definitely heard that it's a good time to hire elm developers. Basically its a kick ass language and a lot of developers love it. However there aren't that many elm jobs out there at the moment, so most elm programmers are doing React / Typescript or something like that. So if you're a company trying to hire elm developers apparently its quite easy.

**Comment by nielsbom** [comment]
I really like this effort. And also: I'm still on the fence wrt Elm :-)

Re:
> What were the common "objections" (besides "React has more packages...").

What I would like to also see (and think is useful for this page) and contribute to is:

- make a list of the objections against Elm (maybe even split out versus other options)
- then try to find as many valid arguments for and against

I would trust a resource like this more if I see pros _and_ cons for a technical option.

Here's a list of discussions, ripe with arguments for and against Elm. I'm willing to distill a list of arguments out of these if that seems useful to y'all.

- [ReasonML vs Elm : reasonml](https://www.reddit.com/r/reasonml/comments/98ju9i/reasonml_vs_elm/)
- [Elm 0.19 Broke Us | Hacker News](https://news.ycombinator.com/item?id=17842400)
- [Do we need to move away from Elm? | Hacker News](https://news.ycombinator.com/item?id=16510267)
- [ReasonML – React as first intended | Hacker News](https://news.ycombinator.com/item?id=17143494)
- [Exploring ReasonML and functional programming | Hacker News](https://news.ycombinator.com/item?id=16333939)
- [Reason ML toolchain | Hacker News](https://news.ycombinator.com/item?id=16316004)
- [Ask HN: ReasonML, ClojureScript, Purescript or Elm? | Hacker News](https://news.ycombinator.com/item?id=17910069)

Because this page is a lot about: "Why choose Elm?" and this is maybe too... discussion heavy? I can totes understand if there's a better other place for this.

**Comment by rtfeldman** [comment]
Here's how I like to evaluate whether to invest in a new technology:

1. **Upside potential.** Those who claim this is great - how great are they claiming? At best, can I expect this to be transformative, or only a slight improvement over what I'd choose instead?
2. **Downside potential.** If things go badly, how bad are we talking? First launch is full of bugs? Works great at first, but falls apart at scale after I've invested a year in it? If I don't end up liking it, how hard would it be to switch to something else?
3. **Up-front investment.** If I try it out, how long will it take me to tell if I've made a good decision or not? How much learning will I have to do before I can ship something? How big a project will I have to build to become comfortable with it?

I balance all three of these and decide whether I want to invest in learning and then trying the thing.

So I don't think pro and con *arguments* are all that helpful - they're a very noisy signal depending on how persuasive someone is, what details they choose to include and omit, etc.

I find anecdotes useful to the extent that themes across different peoples' experiences inform upside and downside potential, and give me some sense of how much investment it'll take to get familiar with the thing.

I'm keenly interested in the specifics of the upsides and the downsides people talk about.

If someone's main praise is "x is pretty nice, I like the syntax" that's very telling. There's a low ceiling on how much a nice syntax can move the productivity needle, so if that's the main upside, this person didn't get much of a boost from it.

Similarly, if their main complaint is "x has too much boilerplate" that's also very telling. People usually complain about more serious problems ("x got painfully slow at scale", "x is super buggy", "I can't untangle the magic to figure out what x is doing", etc) long before they complain about annoyances like boilerplate.

So personally, I'm less interested in a comparison of arguments (e.g. "this person liked x and wrote 3 pages arguing that x makes this language more important than the discovery of penicillin" or "this person disliked y and wrote 3 pages arguing that it's a moral imperative for all programmers to use the author's preferred language instead").

I'm much more interested in summaries of experience reports - e.g. "this person used it for X time on Y project, these things went well and these other things didn't go well". That's the highest signal to noise ratio in my book.

**Comment by kgashok** [comment]
> I really like this effort. And also: I'm still on the fence wrt Elm :-)
> 
> Re:
> 
> > What were the common "objections" (besides "React has more packages...").
> 
> What I would like to also see (and think is useful for this page) and contribute to is:
> 
> * make a list of the objections against Elm (maybe even split out versus other options)
> * then try to find as many valid arguments for and against
> 
> I would trust a resource like this more if I see pros _and_ cons for a technical option.
> 
> Here's a list of discussions, ripe with arguments for and against Elm. I'm willing to distill a list of arguments out of these if that seems useful to y'all.
> 
> * [ReasonML vs Elm : reasonml](https://www.reddit.com/r/reasonml/comments/98ju9i/reasonml_vs_elm/)
> * [Elm 0.19 Broke Us | Hacker News](https://news.ycombinator.com/item?id=17842400)
> * [Do we need to move away from Elm? | Hacker News](https://news.ycombinator.com/item?id=16510267)
> * [ReasonML – React as first intended | Hacker News](https://news.ycombinator.com/item?id=17143494)
> * [Exploring ReasonML and functional programming | Hacker News](https://news.ycombinator.com/item?id=16333939)
> * [Reason ML toolchain | Hacker News](https://news.ycombinator.com/item?id=16316004)
> * [Ask HN: ReasonML, ClojureScript, Purescript or Elm? | Hacker News](https://news.ycombinator.com/item?id=17910069)
> 
> Because this page is a lot about: "Why choose Elm?" and this is maybe too... discussion heavy? I can totes understand if there's a better other place for this.

And [Kevin Lanthier(https://itnext.io/@kevin.lanthier)'s journey in moving from  [JavaScript to TypeScript to Elm](https://itnext.io/from-javascript-to-typescript-to-elm-5c36fca70b4a)?

**Comment by martin-displayr** [comment]
Sydney Elm Meetup: https://www.meetup.com/en-AU/Sydney-Elm-Meetup/

**Comment by kjda** [comment]
> chartbehavior.com

what are you using for the charts?

**Comment by popara** [comment]
Hand rolled charts on SVG.
Ofcourse in Elm :)

**Comment by yaitskov** [comment]
Is there an example with multiple bundles and dynamic loading plus extracting strings for translation and grouping by bundle borders?

**Comment by nelsonic** [comment]
@yaitskov that seems like a good question to ask on the Elm Forum: https://discourse.elm-lang.org/

**Comment by ancatrusc** [comment]
And Richard Feldman's interview about [his book](https://gotopia.tech/bookclub/episodes/upgrade-your-frontend-game-be-an-elm-wizard).

**Comment by dangdennis** [comment]
What's the landscape like now for readily available Elm UI libraries? Are there enough building blocks like Ant.design / MUI in Elm? 

Elm easily solves all the data manipulation and stateful work amazingly, but a team wouldn't want to re-implement many of the available components & views in the aforementioned libraries.

**Comment by artfuldev** [comment]
Has anything changed in 2024?

**Comment by nelsonic** [comment]
Hi @artfuldev 👋 good question. 💭 

One of the _strengths_ of`Elm` is that it's (pretty much) feature-complete and stable. 
It's been stable for the last few years and very little has changed; that's a _really good_ thing!
It means projects written in `Elm` don't have dependencies constantly being updated the way [`React/Next.js`](https://github.com/dwyl/learn-nextjs/issues/12) does ...

The [calculator](https://github.com/artfuldev/functional-calculator/) you wrote 4 years ago still works flawlessly in 2024. 🚀 
If you'd written it in `React` and tried to run it now,
you'd have to update _dozens_ of dependencies
and almost certainly have breaking changes to fix. 😢 

There are still _many_ [companies](https://github.com/jah2488/elm-companies) depending on `Elm` in production. 
Questions are asked/answered frequently on the forum: https://discourse.elm-lang.org
Plenty of people know `Elm` and it's _easy/fast_ to train new (_motivated_) devs to learn it
especially given the proliferation of other functional programming in other languages like [`Elixir`](https://github.com/dwyl/learn-elixir/issues/102). 

[NoRedInk](https://www.noredink.com/) where many `Elm` people work still uses `Elm` for all their apps
and their product is used in ***60% of US school districts***: 
<img width="686" alt="image" src="https://github.com/user-attachments/assets/aabbb0ab-365b-4ece-911a-082042fb5fa3">

They've built an _incredibly_ useful product that generates real value to teachers and students and is ***profitable***.
That's more than we can say about 95% of startups chasing the next Crypto/NFT/AI craze ... 🙄 

Sadly, some "bosses" or "executives" see the _lack_ of changes in `Elm` as a _bad_ thing
like it's not being maintained/extended ... so they don't want to use it.
But if something "just works" and doesn't _need_ to be updated, I see that as a _major_ benefit. 
Stability and maintainability beats bells and whistles every time for mission critical software. 

> **Note**: Really wish [Evan](https://github.com/evancz) would just call it `v1.0` to reflect the stability. 
> He doesn't seem to be in any rush to call it `1.0`; see: [`roadmap.md`](https://github.com/elm/projects/blob/0d0f52abb320d1370aa7b6abc7e1007ba4c524ab/roadmap.md)

We were _considering_ using `Elm` for a recent green-field client project because it's (still) _awesome_, 😍 
but were forced to use `TypeScript` (inferior in every way) because "devs already know it" ... 

@rtfeldman noted this in his talk "Predicting the Future of the Web": https://youtu.be/okrB3aJtUaw?t=1352

## "_I don't think `Elm` is going to take over the world, I think `TypeScript` will ..._"

<img width="962" alt="image" src="https://github.com/user-attachments/assets/2fe1d6f4-99b8-4de6-a8b4-f4ba6f7eaec6">

## "_The point is not to win a popularity contest, it's to find a technology that you will be happy with for the next 5-10 years etc._"

The points made by Richard in his talk in 2019 are still just as valid in 2024 and beyond.
We get updates to our `TypeScript` projects every month and that all takes time away from building features.
Whereas our `Elm` apps are ticking away nicely in production with zero dependency updates in _years_.

# But ... HackerNews Said ... 

The counterargument to `Elm` are described in: https://lukeplant.me.uk/blog/posts/why-im-leaving-elm 
and discussed in: https://news.ycombinator.com/item?id=22821447
None of the people commenting on HN have written a _beautiful & useful_ programming language
So take their opinion for what it is; opinion. 💬 

`Evan` is a Mozart of code and language design and has influenced _many_ other languages,
e.g: https://en.wikipedia.org/wiki/Rust_(programming_language)
<img width="920" alt="rust-lang-influenced-by-elm" src="https://github.com/user-attachments/assets/4f872d75-c349-4f02-8847-ce857a8af31d">
`Elm` is still just as useful and relevant in 2024 as it was 5 years ago and will still be in another 5 years!
When I teach my kids to code in a couple of years time, I'm _definitely_ going to teach them `Elm` (after `Scratch`) ...

If you are building something for the web in a small team of _motivated_ engineers, `Elm` is still an _excellent_ choice. ❤️

**Comment by popara** [comment]
I will second that. 

My product is still using Elm for its most complex UI elements and client side logic - going longer than 6 years now! 

With the advent of HTMX I have scaled down client-side logic significantly but whenever I need to fix, update, maintain my Elm code it is still a pure pleasure!

**Comment by dbj** [comment]
I agree. At XetiCode, we use Elm with our clients as much as possible. We also use it for all our internal projects. The community is strong and keeps building out a great platform while the language stays stable.

**Comment by nick-walt** [comment]
If we look at Elm as just a language it seems to have stagnated in 2019 at version 0.19.

However, if we look at Elm as an entire platform and the language as a component we can see that the foundation has been completed.

The rest of the platform is still being developed and polished. This includes the innovative tooling, libraries and framework enhancements that continuously improve the scope of the fundamental language.

The Elm language is quiet. The Elm platform is busy and innovative.

Elm's stable language base will support a lot of innovation in the years to come that will remain cohesive and integral as the platform's scope increases.

**Comment by gabriela-sartori** [comment]
At Uncover, we still use Elm for all our apps.
Our domain is very complex, and it makes us develop features, do huge refactors and maintain the product with less developers, with a much higher quality.

**Comment by sporto** [comment]
I mantain two apps at work. One written in Elm and the other one in React.

The Elm app has almost no bugs, it is easy to change and very robust, doesn't have constant depencency changes.
The React app has new bugs all the time, has a constant churn of dependency updates, it is hard to work on.

If will definitelly chose Elm over React today.
